import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
import { ChevronDown } from "lucide-react";
import { Link } from "react-router-dom";
function CartForm({ dir = "rtl" }) {
    const payments = ["الدفع نقدا عند الاستلام"];
    const governorates = ["القاهرة", "الجيزة", "الإسكندرية"];
    const areas = ["مدينة نصر", "المعادي", "التجمع"];
    const [activePayment, setActivePayment] = useState(payments[0]);
    const [gov, setGov] = useState("");
    const [area, setArea] = useState("");
    const [openGov, setOpenGov] = useState(false);
    const [openArea, setOpenArea] = useState(false);
    return (_jsxs("div", { dir: dir, className: "\r\n        border\r\n        border-orange\r\n        rounded-lg\r\n        overflow-hidden\r\n        flex\r\n        flex-col\r\n        gap-6\r\n        p-10\r\n        w-[85%]\r\n        mx-auto \r\n    \r\n      ", children: [_jsx("h2", { className: "text-center text-blue font-bold font-arabic text-[26px]", children: "\u0625\u062A\u0645\u0627\u0645 \u0627\u0644\u0634\u0631\u0627\u0621" }), _jsxs("div", { className: "flex flex-col gap-3", children: [_jsx("p", { className: "text-blue font-bold font-arabic text-[20px] py-1", children: "\u0634\u062D\u0646 \u0625\u0644\u0649" }), _jsxs("div", { className: "relative w-full", children: [_jsxs("div", { onClick: () => setOpenGov(!openGov), className: "flex items-center justify-between border rounded-md px-4 h-[44px] text-gray-600 cursor-pointer", children: [_jsx("span", { className: "text-[14px] font-medium", children: gov || "المحافظة" }), _jsx(ChevronDown, { size: 18 })] }), openGov && (_jsx("div", { className: "absolute left-0 mt-1 w-full bg-white border rounded-md overflow-hidden shadow-md z-20", children: governorates.map((item) => (_jsx("div", { onClick: () => {
                                        setGov(item);
                                        setOpenGov(false);
                                    }, className: `px-4 h-[40px] flex items-center cursor-pointer transition
                    ${gov === item
                                        ? "bg-orange text-white"
                                        : "hover:bg-orange-100"}`, children: item }, item))) }))] }), _jsxs("div", { className: "relative w-full", children: [_jsxs("div", { onClick: () => setOpenArea(!openArea), className: "flex items-center justify-between border rounded-md px-4 h-[44px] text-gray-600 cursor-pointer", children: [_jsx("span", { className: "text-[14px] font-medium", children: area || "المنطقة" }), _jsx(ChevronDown, { size: 18 })] }), openArea && (_jsx("div", { className: "absolute left-0 mt-1 w-full bg-white border rounded-md overflow-hidden shadow-md z-20", children: areas.map((item) => (_jsx("div", { onClick: () => {
                                        setArea(item);
                                        setOpenArea(false);
                                    }, className: `px-4 h-[40px] flex items-center cursor-pointer transition
                    ${area === item
                                        ? "bg-orange text-white"
                                        : "hover:bg-orange-100"}`, children: item }, item))) }))] }), _jsx("input", { type: "text", placeholder: "\u0627\u0633\u0645 \u0627\u0644\u0634\u0627\u0631\u0639", className: "border rounded-md p-3 text-sm outline-none" }), _jsx("input", { type: "text", placeholder: "\u0631\u0642\u0645 \u0627\u0644\u0639\u0645\u0627\u0631\u0629\u060C \u0627\u0644\u062F\u0648\u0631", className: "border rounded-md p-3 text-sm outline-none" })] }), _jsxs("div", { className: "flex flex-col gap-3 py-1", children: [_jsx("p", { className: "text-blue font-bold font-arabic text-[20px] text-start", children: "\u0637\u0631\u064A\u0642\u0629 \u0627\u0644\u062F\u0641\u0639" }), payments.map((item) => {
                        const isActive = activePayment === item;
                        return (_jsxs("label", { onClick: () => setActivePayment(item), className: "flex items-center justify-start gap-3 cursor-pointer", children: [_jsx("div", { className: "w-[32px] h-[32px] rounded-[14px] border-2 border-blue bg-white flex items-center justify-center", children: isActive && (_jsx("div", { className: "w-[22px] h-[22px] bg-orange rounded-[10px]" })) }), _jsx("span", { className: "text-blue font-semibold font-arabic text-[18px]", children: item })] }, item));
                    })] }), _jsxs("div", { className: "flex flex-row-reverse border rounded-md overflow-hidden items-center", children: [_jsx("button", { className: "bg-orange text-white font-bold font-arabic px-6 py-2 text-sm m-2 rounded-md", children: "\u062A\u0641\u0639\u064A\u0644" }), _jsx("input", { type: "text", placeholder: "\u0627\u0643\u062A\u0628 \u0643\u0648\u062F \u0627\u0644\u062E\u0635\u0645", className: "flex-1 px-3 py-2 text-sm outline-none" })] }), _jsxs("div", { className: "flex flex-col gap-3", children: [_jsx("p", { className: "text-blue font-bold font-arabic text-[26px] text-center py-1", children: "\u0645\u0644\u062E\u0635 \u0627\u0644\u0637\u0644\u0628\u064A\u0629" }), _jsxs("div", { className: "flex justify-between text-sm", children: [_jsx("span", { className: "text-blue font-semibold font-arabic text-[18px]", children: "\u0631\u0633\u0648\u0645 \u0627\u0644\u0634\u062D\u0646" }), _jsx("span", { className: "text-teal font-semibold font-arabic text-[18px]", children: "EGP00.00" })] }), _jsxs("div", { className: "flex justify-between text-sm", children: [_jsx("span", { className: "text-blue font-semibold font-arabic text-[18px]", children: "\u0627\u0644\u0636\u0631\u064A\u0628\u0629" }), _jsx("span", { className: "text-teal font-semibold font-arabic text-[18px]", children: "EGP00.00" })] }), _jsx("hr", {}), _jsxs("div", { className: "flex justify-between text-sm font-semibold", children: [_jsx("span", { className: "text-blue font-bold font-arabic text-[18px]", children: "\u0627\u0644\u0625\u062C\u0645\u0627\u0644\u064A" }), _jsx("span", { className: "text-teal font-semibold font-arabic text-[18px]", children: "EGP00.00" })] })] }), _jsx(Link, { to: "/order-placed", children: _jsx("button", { className: "bg-orange text-white py-3 rounded-md font-bold text-[20px] hover:opacity-90 transition w-full", children: "\u0625\u062A\u0645\u0627\u0645 \u0627\u0644\u0634\u0631\u0627\u0621" }) })] }));
}
export default CartForm;
